### PR TITLE
[docs] fix replica port number in readme

### PR DESCRIPTION
**Pull request by lookfirst**
sorry for the single character fix. i'm kind of ocd about this stuff.

### CODE REVIEW

**Comment by guycipher** [comment]
@lookfirst the example is correct the replica would be on another port not the same one.  Hence it being a replica.

**Comment by guycipher** [comment]
You wouldn’t be able to start 2 listeners on the same port.  Am I ok to close this PR @lookfirst ? Thank you by the way I appreciate any PRs or corrections on anything.

**Comment by lookfirst** [comment]
I'm super confused then. Why is it marked as 7683?

2024-01-05 at 07 08 42 png

**Comment by guycipher** [comment]
https://github.com/cursusdb/cursusdb/commit/88067ff4470550d365391ed067392e08de4bfa6b will help ya

**Comment by lookfirst** [comment]
Sure, that adds more to exactly what I had suggested.

**Comment by guycipher** [comment]
The node has a kept alive connection to the replica for automatic sync and the cluster has kept alive connections to node and node replicas.

**Pull request closed without merging**
